Updating to latest changes from forked repo
- Updated Dockerfile to use kylemanna/openvpn:latest which bumped Alpine to 3.5 requiring a change to the pip installation.
- Modified iptables to avoid running if the OVPN_SERVER was not obtained from either environment variable or consul template.
- Modified OPENVPN_CERT_SOURCE OPENVPN_CONFIG_SOURCE to use Environment variable value if available and if not use consul to obtain.

diff --git a/bin/ovpn_run_consul b/bin/ovpn_run_consul
--- a/bin/ovpn_run_consul
+++ b/bin/ovpn_run_consul
@@ -79,9 +79,8 @@ fi
 
 # Grab all of the keys from s3 with aws-cli 
 if [ "${CONSUL_PREFIX}" ];then 
-    OPENVPN_CERT_SOURCE=$(/usr/local/bin/envconsul -sanitize -pristine -upcase -once -prefix ${CONSUL_PREFIX}/${1} env | grep OPENVPN_CERT_SOURCE | awk -F = '{print $NF}')
+    OPENVPN_CERT_SOURCE=${OPENVPN_CERT_SOURCE:-"$(/usr/local/bin/envconsul -sanitize -pristine -upcase -once -prefix ${CONSUL_PREFIX}/${1} env | grep OPENVPN_CERT_SOURCE | awk -F = '{print $NF}')"}
     if [ "${OPENVPN_CERT_SOURCE}" ]; then 
-        OVPN_OPENVPN_USER=$(/usr/local/bin/envconsul -sanitize -pristine -upcase -once -prefix ${CONSUL_PREFIX}/${1} env | grep OVPN_OPENVPN_USER | awk -F = '{print $NF}')
         aws s3 cp "${OPENVPN_CERT_SOURCE}" "$OPENVPN/keys" --recursive
         chmod 0700 "$OPENVPN/keys"
         if [ -r "$OPENVPN/keys/crl.pem" ]; then
@@ -92,13 +91,13 @@ if [ "${CONSUL_PREFIX}" ];then
     fi
     # Grab the server configuration from consul as well
     # requires mounting a config directory in /tmp/consul_openvpn
-    OPENVPN_CONFIG_SOURCE=$(/usr/local/bin/envconsul -sanitize -pristine -upcase -once -prefix ${CONSUL_PREFIX}/${1} env | grep OPENVPN_CONFIG_SOURCE | awk -F = '{print $NF}')
+    OPENVPN_CONFIG_SOURCE=${OPENVPN_CONFIG_SOURCE:-"$(/usr/local/bin/envconsul -sanitize -pristine -upcase -once -prefix ${CONSUL_PREFIX}/${1} env | grep OPENVPN_CONFIG_SOURCE | awk -F = '{print $NF}')"}
     if [ "${OPENVPN_CONFIG_SOURCE}" ]; then
         aws s3 cp "${OPENVPN_CONFIG_SOURCE}" "${OPENVPN}/consul_configs" --recursive
         consul-template -template "${OPENVPN}/consul_configs/openvpn_server_consul.tpl:${OPENVPN}/openvpn.conf" -once
     fi
     # Set the OVPN_SERVER variable from consul KV 
-    OVPN_SERVER=$(/usr/local/bin/envconsul -sanitize -pristine -upcase -once -prefix ${CONSUL_PREFIX}/${1} env | grep OVPN_OPENVPN_SERVER_IP_SUBNET | awk -F = '{print $NF}')
+    OVPN_SERVER=${OVPN_SERVER:-"$(/usr/local/bin/envconsul -sanitize -pristine -upcase -once -prefix ${CONSUL_PREFIX}/${1} env | grep OVPN_OPENVPN_SERVER_IP_SUBNET | awk -F = '{print $NF}')"}
 else    
     # Use a hacky hardlink as the CRL Needs to be readable by the user/group
     # OpenVPN is running as.  Only pass arguments to OpenVPN if it's found.
@@ -115,14 +114,19 @@ fi
 
 #Setup NAT forwarding if requested
 if [ "$OVPN_DEFROUTE" != "0" ] || [ "$OVPN_NAT" == "1" ] ; then
-    iptables -t nat -C POSTROUTING -s $OVPN_SERVER -o $OVPN_NATDEVICE -j MASQUERADE || {
-      iptables -t nat -A POSTROUTING -s $OVPN_SERVER -o $OVPN_NATDEVICE -j MASQUERADE
-    }
-    for i in "${OVPN_ROUTES[@]}"; do
-        iptables -t nat -C POSTROUTING -s "$i" -o $OVPN_NATDEVICE -j MASQUERADE || {
-          iptables -t nat -A POSTROUTING -s "$i" -o $OVPN_NATDEVICE -j MASQUERADE
+    if [ "${OVPN_SERVER}" ]; then
+        iptables -t nat -C POSTROUTING -s $OVPN_SERVER -o $OVPN_NATDEVICE -j MASQUERADE || {
+        iptables -t nat -A POSTROUTING -s $OVPN_SERVER -o $OVPN_NATDEVICE -j MASQUERADE
         }
-    done
+        for i in "${OVPN_ROUTES[@]}"; do
+            iptables -t nat -C POSTROUTING -s "$i" -o $OVPN_NATDEVICE -j MASQUERADE || {
+            iptables -t nat -A POSTROUTING -s "$i" -o $OVPN_NATDEVICE -j MASQUERADE
+            }
+        done
+    else 
+        echo "Unable to set OVPN_SERVER Not Set"
+        exit 1 
+    fi
 fi
 
 ip -6 route show default 2>/dev/null
